# Generated by Django 4.1.1 on 2023-08-28 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('method', models.CharField(default=None, max_length=100)),
                ('pay', models.BigIntegerField(default=None)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='order_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_order_in_order_payment', to='orders.order')),
                ('id_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_payment_in_order_payment', to='payments.payment')),
            ],
            options={
                'db_table': 'order_payment',
            },
        ),
    ]
