# Generated by Django 4.1.1 on 2023-08-28 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('address', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('department', models.CharField(default=None, max_length=100)),
                ('country', models.CharField(default=None, max_length=100)),
                ('code', models.BigIntegerField(default=None, unique=True)),
                ('state', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='order_shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_order_in_order_shipment', to='orders.order')),
                ('id_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_shipment_in_order_shipment', to='shipments.shipment')),
            ],
            options={
                'db_table': 'order_shipment',
            },
        ),
    ]
