# Generated by Django 4.1.1 on 2023-08-28 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('code', models.BigIntegerField(default=None, unique=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_in_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_order_in_order_product', to='orders.order')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_product_in_order_product', to='products.product')),
            ],
            options={
                'db_table': 'order_product',
            },
        ),
    ]
