# Generated by Django 4.1.1 on 2023-08-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=500)),
                ('code', models.BigIntegerField(default=None, unique=True)),
                ('price', models.BigIntegerField(default=None)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
